//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateTable
    {
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public string StatName { get; set; }
    }
}
